pipeline {
    agent any
    
    stages {
        stage('Clone Repo') {
            steps {
                checkout scm
                sh 'ls *'
                echo 'Repo cloned'
            }
        }
        stage('Build Image') {
            steps {
		//sh 'docker build -t rudiheydra/jenkinstest ./pushdockerimage/' (this will use the tag latest)
		sh 'docker build -t rudiheydra/jenkins-image-push:$BUILD_NUMBER ./build-docker-image/'
                echo 'Image built'
            }
        }
        
    }
        
        
}

